FROM python:3.9
COPY ./* /scraper/
WORKDIR /scraper
RUN mkdir ./tools
RUN pip install --no-cache-dir --upgrade -r /scraper/requirements.txt

RUN python -m spacy download en_core_web_sm
RUN python -m spacy download fr_core_news_sm
RUN python -m spacy download de_core_news_sm
RUN python -m spacy download it_core_news_sm

RUN python -m nltk.downloader all

RUN python scraper.py


